apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-jupyter-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/jupyter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-jupyter-volume
  namespace: ai-jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
